### ISSUE TITLE
'ParseInput (Parse input test)' issue

### ISSUE THREAD

**Issue by kiekyon** [bbglab/intogen-plus#42]
Hi - I am encountering this error when running the intogen.nf on the test dataset. 
any thoughts?

Thanks very much

intogen-plus-master$ nextflow run intogen.nf -resume -profile local --input test/ --output ./output
N E X T F L O W  ~  version 21.10.6
Launching `intogen.nf` [determined_church] - revision: 2352904c63
executor >  local (1)
[c8/22bc37] process > ParseInput (Parse input test) [  0%] 0 of 1
[-        ] process > LoadCancer                    -
[-        ] process > LoadPlatform                  -
[-        ] process > LoadGenome                    -
[-        ] process > ProcessVariants               -
[-        ] process > FormatSignature               -
[-        ] process > ComputeProfile                -
[-        ] process > FormatFML                     -
[-        ] process > OncodriveFML                  -
[-        ] process > FormatCLUSTL                  -
[-        ] process > OncodriveCLUSTL               -
[-        ] process > FormatDNDSCV                  -
[-        ] process > dNdScv                        -
[-        ] process > FormatVEP                     -
[-        ] process > VEP                           -
[-        ] process > ProcessVEPoutput              -
[-        ] process > FilterNonSynonymous           -
[-        ] process > FormatSMRegions               -
[-        ] process > SMRegions                     -
[-        ] process > FormatCBaSE                   -
[-        ] process > CBaSE                         -
[-        ] process > FormatMutPanning              -
[-        ] process > MutPanning                    -
[-        ] process > FormatHotMAPS                 -
[-        ] process > HotMAPS                       -
[-        ] process > Combination                   -
[-        ] process > FormatdeconstructSigs         -
[-        ] process > deconstructSigs               -
[-        ] process > CohortCounts                  -
[-        ] process > CohortSummary                 -
[-        ] process > MutationsSummary              -
[-        ] process > DriverDiscovery               -
[-        ] process > DriverSummary                 -
[-        ] process > ParseProfile                  -
[-        ] process > DriverSaturation              -
[-        ] process > FilterMNVS                    -
WARN: There's no process matching config selector: Signature
Error executing process > 'ParseInput (Parse input test)'

Caused by:
  Process `ParseInput (Parse input test)` terminated with an error exit status (1)

Command executed:

  openvar groupby test --header -g DATASET -q -s 'gzip > ${GROUP_KEY}.parsed.tsv.gz'

Command exit status:
  1

Command output:
  (empty)

Command error:
      sys.exit(openvar())
               ~~~~~~~^^
    File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
             ~~~~~~~~~^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.13/site-packages/openvariant/commands/openvar.py", line 84, in groupby
      for group_key, group_result, command in group_by_task(input_path, annotations, script, key_by=group_by, where=where,
                                              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                            cores=cores, quite=quite, header=header):
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/openvariant/tasks/groupby.py", line 149, in group_by
      selection = _group(base_path, annotation_path, key_by)
    File "/usr/local/lib/python3.13/site-packages/openvariant/tasks/groupby.py", line 38, in _group
      for file, ann in findfiles(base_path, annotation_path):
                       ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 84, in findfiles
      for f, a in _find_files(base_path, annotation, fix):
                  ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 62, in _find_files
      for f, a in _scan_files(base_path, annotation, fix):
                  ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 37, in _scan_files
      for f, a in _scan_files(file_path, annotation, fix):
                  ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 37, in _scan_files
      for f, a in _scan_files(file_path, annotation, fix):
                  ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 37, in _scan_files
      for f, a in _scan_files(file_path, annotation, fix):
                  ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 31, in _scan_files
      annotation = Annotation(annotation_file)
    File "/usr/local/lib/python3.13/site-packages/openvariant/annotation/annotation.py", line 170, in __init__
      AnnotationTypesBuilders[k[AnnotationKeys.TYPE.value].upper()].value(k, self._path)
      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/enum.py", line 782, in __getitem__
      return cls._member_map_[name]
             ~~~~~~~~~~~~~~~~^^^^^^
  KeyError: 'INTERNAL'
  INFO:    Cleaning up image...

Work dir:
  intogen-plus-master/work/c8/22bc37ea6f3afbc9bbe9cc639baa4c

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by FedericaBrando** [comment]
Hi @kiekyon ,

Thanks for reaching out to us, did you go through [the building step](https://github.com/bbglab/intogen-plus/blob/master/build/README.rst) before running the pipeline? did you export the variables INTOGEN_DATASETS and INTOGEN_CONTAINERS? 

Thanks,

Fede

**Comment by FedericaBrando** [comment]
Hi Kiekyon,

I see, from reading your error, it seems like there is a problem with the [annotation file](https://github.com/bbglab/intogen-plus/blob/master/test/pipeline/input/cbioportal_prad_broad/metadata.yaml), Although I was not able to reproduce it locally. Can you confirm that is the same as the one in the repo?

Moreover, try to run the following:
```
nextflow run intogen.nf -profile local --input test/pipeline --output ./output
```

Just to be sure that openvariant is correctly iterating the right folder to parse the data. 
please let me know if you keep having the error,

Federica

**Comment by kiekyon** [comment]
Thanks. I have now replaced the metadata.yaml and data_mutations_extended.txt with the files in the link. 

Unfortunately, running both the following return the same 'KeyError:Internal' error as above

nextflow run intogen.nf -profile local --input test --output ./output
nextflow run intogen.nf -profile local --input test/pipeline --output ./output

**Comment by FedericaBrando** [comment]
Can you paste the output of the following files (you can find it in the `work` folder of the process - it's the path in the log):
- `.command.err`
- `.command.out`
- `.command.sh`
- `.command.run`

moreover, could you shell into the intogen-core container and check for the version of openvariant? 

Another thing that can be done is redo the build of the containers, I am not able to reproduce with the latest version of the containers, it would be great to know the exact version you are using.

**Comment by kiekyon** [comment]
Thanks for the suggestions. I pasted the contents of the four files below.

The Singularity shell uses openvar, version 1.0.0.
If it helps, I am using Python 3.13.0, Nextflow Version: 22.10.6 build 5843, and openjdk 17.0.3-internal 2022-04-19
The latest version of intogen from the github was used (19th Sept 2024). Will try re-building from scratch.

**.command.err**

INFO:`    Converting SIF file to temporary sandbox...
Traceback (most recent call last):
  File "/usr/local/bin/openvar", line 8, in <module>
    sys.exit(openvar())
             ~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/openvariant/commands/openvar.py", line 84, in groupby
    for group_key, group_result, command in group_by_task(input_path, annotations, script, key_by=group_by, where=where,
                                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                          cores=cores, quite=quite, header=header):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openvariant/tasks/groupby.py", line 149, in group_by
    selection = _group(base_path, annotation_path, key_by)
  File "/usr/local/lib/python3.13/site-packages/openvariant/tasks/groupby.py", line 38, in _group
    for file, ann in findfiles(base_path, annotation_path):
                     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 84, in findfiles
    for f, a in _find_files(base_path, annotation, fix):
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 62, in _find_files
    for f, a in _scan_files(base_path, annotation, fix):
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 37, in _scan_files
    for f, a in _scan_files(file_path, annotation, fix):
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 37, in _scan_files
    for f, a in _scan_files(file_path, annotation, fix):
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openvariant/find_files/find_files.py", line 31, in _scan_files
    annotation = Annotation(annotation_file)
  File "/usr/local/lib/python3.13/site-packages/openvariant/annotation/annotation.py", line 170, in __init__
    AnnotationTypesBuilders[k[AnnotationKeys.TYPE.value].upper()].value(k, self._path)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 782, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'INTERNAL'
INFO:    Cleaning up image...

**.command.out**
(empty file)

**.command.sh**
#!/bin/bash -ue
openvar groupby pipeline --header -g DATASET -q -s 'gzip > ${GROUP_KEY}.parsed.tsv.gz'

**.command.run**
#!/bin/bash
# NEXTFLOW TASK: ParseInput (Parse input pipeline)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_tree() {
    local pid=$1

    declare -a ALL_CHILDREN
    while read P PP;do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    pstat() {
        local x_pid=$1
        local STATUS=$(2> /dev/null < /proc/$1/status egrep 'Vm|ctxt')

        if [ $? = 0 ]; then
        local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
        local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
        local x_peak=$(echo "$STATUS" | egrep 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
        local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
        local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
        fi
    }

    pwalk() {
        pstat $1
        for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
    }

    pwalk $1
}

nxf_stat() {
    cpu_stat=()
    nxf_tree $1

    declare -a sum=(0 0 0 0 0 0 0 0)
    local pid
    local i
    for pid in "${!cpu_stat[@]}"; do
        local row=(${cpu_stat[pid]})
        [ $NXF_DEBUG = 1 ] && echo "++ stat mem=${row[*]}"
        for i in "${!row[@]}"; do
        if [ $i != 0 ]; then
            sum[i]=$((sum[i]+row[i]))
        fi
        done
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat SUM=${sum[*]}"

    for i in {1..7}; do
        if [ ${sum[i]} -lt ${cpu_peak[i]} ]; then
            sum[i]=${cpu_peak[i]}
        else
            cpu_peak[i]=${sum[i]}
        fi
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat PEAK=${sum[*]}\n"
    nxf_stat_ret=(${sum[*]})
}

nxf_mem_watch() {
    set -o pipefail
    local pid=$1
    local trace_file=.command.trace
    local count=0;
    declare -a cpu_stat=(0 0 0 0 0 0 0 0)
    declare -a cpu_peak=(0 0 0 0 0 0 0 0)
    local mem_tot=$(< /proc/meminfo grep MemTotal | awk '{print $2}')
    local timeout
    local DONE
    local STOP=''

    [ $NXF_DEBUG = 1 ] && nxf_sleep 0.2 && ps fx

    while true; do
        nxf_stat $pid
        if [ $count -lt 10 ]; then timeout=1;
        elif [ $count -lt 120 ]; then timeout=5;
        else timeout=30;
        fi
        read -t $timeout -r DONE || true
        [[ $DONE ]] && break
        if [ ! -e /proc/$pid ]; then
            [ ! $STOP ] && STOP=$(nxf_date)
            [ $(($(nxf_date)-STOP)) -gt 10000 ] && break
        fi
        count=$((count+1))
    done

    echo "%mem=${nxf_stat_ret[1]}"      >> $trace_file
    echo "vmem=${nxf_stat_ret[2]}"      >> $trace_file
    echo "rss=${nxf_stat_ret[3]}"       >> $trace_file
    echo "peak_vmem=${nxf_stat_ret[4]}" >> $trace_file
    echo "peak_rss=${nxf_stat_ret[5]}"  >> $trace_file
    echo "vol_ctxt=${nxf_stat_ret[6]}"  >> $trace_file
    echo "inv_ctxt=${nxf_stat_ret[7]}"  >> $trace_file
}

nxf_write_trace() {
    echo "nextflow.trace/v2"           > $trace_file
    echo "realtime=$wall_time"         >> $trace_file
    echo "%cpu=$ucpu"                  >> $trace_file
    echo "rchar=${io_stat1[0]}"        >> $trace_file
    echo "wchar=${io_stat1[1]}"        >> $trace_file
    echo "syscr=${io_stat1[2]}"        >> $trace_file
    echo "syscw=${io_stat1[3]}"        >> $trace_file
    echo "read_bytes=${io_stat1[4]}"   >> $trace_file
    echo "write_bytes=${io_stat1[5]}"  >> $trace_file
}

nxf_trace_mac() {
    local start_millis=$(nxf_date)

    /bin/bash -ue /home/hkk/dnds/intogen-plus-master/work/a2/64005a6e87959ae665428b76999b3d/.command.sh

    local end_millis=$(nxf_date)
    local wall_time=$((end_millis-start_millis))
    local ucpu=''
    local io_stat1=('' '' '' '' '' '')
    nxf_write_trace
}

nxf_fd() {
    local FD=11
    while [ -e /proc/$$/fd/$FD ]; do FD=$((FD+1)); done
    echo $FD
}

nxf_trace_linux() {
    local pid=$$
    command -v ps &>/dev/null || { >&2 echo "Command 'ps' required by nextflow to collect task metrics cannot be found"; exit 1; }
    local num_cpus=$(< /proc/cpuinfo grep '^processor' -c)
    local tot_time0=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time0=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local io_stat0=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local start_millis=$(nxf_date)
    trap 'kill $mem_proc' ERR
    
    /bin/bash -ue /home/hkk/dnds/intogen-plus-master/work/a2/64005a6e87959ae665428b76999b3d/.command.sh &
    local task=$!

    mem_fd=$(nxf_fd)
    eval "exec $mem_fd> >(nxf_mem_watch $task)"
    local mem_proc=$!

    wait $task

    local end_millis=$(nxf_date)
    local tot_time1=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time1=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local ucpu=$(awk -v p1=$cpu_time1 -v p0=$cpu_time0 -v t1=$tot_time1 -v t0=$tot_time0 -v n=$num_cpus 'BEGIN { pct=(p1-p0)/(t1-t0)*100*n; printf("%.0f", pct>0 ? pct : 0) }' )

    local io_stat1=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local i
    for i in {0..5}; do
        io_stat1[i]=$((io_stat1[i]-io_stat0[i]))
    done

    local wall_time=$((end_millis-start_millis))
    [ $NXF_DEBUG = 1 ] && echo "+++ STATS %CPU=$ucpu TIME=$wall_time I/O=${io_stat1[*]}"

    echo "nextflow.trace/v2"           > $trace_file
    echo "realtime=$wall_time"         >> $trace_file
    echo "%cpu=$ucpu"                  >> $trace_file
    echo "rchar=${io_stat1[0]}"        >> $trace_file
    echo "wchar=${io_stat1[1]}"        >> $trace_file
    echo "syscr=${io_stat1[2]}"        >> $trace_file
    echo "syscw=${io_stat1[3]}"        >> $trace_file
    echo "read_bytes=${io_stat1[4]}"   >> $trace_file
    echo "write_bytes=${io_stat1[5]}"  >> $trace_file

    [ -e /proc/$mem_proc ] && eval "echo 'DONE' >&$mem_fd" || true
    wait $mem_proc 2>/dev/null || true
    while [ -e /proc/$mem_proc ]; do nxf_sleep 0.1; done
}

nxf_trace() {
    local trace_file=.command.trace
    touch $trace_file
    if [[ $(uname) = Darwin ]]; then
        nxf_trace_mac
    else
        nxf_trace_linux
    fi
}
nxf_container_env() {
cat << EOF
export INTOGEN_DATASETS="/home/hkk/dnds/intogen-plus-master/datasets"
export BGDATA_LOCAL="/home/hkk/dnds/intogen-plus-master/datasets/bgdata"
export BGDATA_OFFLINE="TRUE"
export PATH="\$PATH:/home/hkk/dnds/intogen-plus-master/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /home/hkk/dnds/intogen-plus-master/work/a2/64005a6e87959ae665428b76999b3d/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && kill $pid 2>/dev/null
}

nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} SINGULARITYENV_NXF_DEBUG=${NXF_DEBUG:=0} singularity exec /home/hkk/dnds/intogen-plus-master/containers/intogen-core.simg /bin/bash -c "cd $PWD; eval $(nxf_container_env); /bin/bash /home/hkk/dnds/intogen-plus-master/work/a2/64005a6e87959ae665428b76999b3d/.command.run nxf_trace"
}

nxf_stage() {
    true
    # stage input files
    rm -f pipeline
    rm -f metadata.yaml
    ln -s /home/hkk/dnds/intogen-plus-master/test/pipeline pipeline
    ln -s /home/hkk/dnds/intogen-plus-master/test/pipeline/input/cbioportal_prad_broad/metadata.yaml metadata.yaml
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/hkk/dnds/intogen-plus-master/work/a2/64005a6e87959ae665428b76999b3d/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY

**Comment by FedericaBrando** [comment]
Okay, I manage to reproduce your error. Apparently there is a problem when running openvariant with python 3.13. 

I created an environment with the latest version of python and latest version of openvariant and I got your same error. This does not happen with python 3.12.

I will add a patch to the container recipe to use python=3.12. 

in the meantime you can rebuild the container by specifying the python version in the /build/containers/core/Singuarity.

```Dockerfile
Bootstrap: docker
From: python:3.12
```

This should fix it! Thanks a lot for reporting :)

**Comment by kiekyon** [comment]
Thanks very much for debugging this error. 

Indeed, using python 3.12 solve the issue.
