### ISSUE TITLE
Error in Combination step

### ISSUE THREAD

**Issue by RyulKim-Inocras** [bbglab/intogen-plus#47]
Hi,

I encounterd a error in combination step. 

I called somatic variants with mutect2 and strelka2 with default setting, and merged them to generate input maf files for intogen pipeine. 
There are all genes (not only cancer gene census) in the input maf file.

The error occured in "assert not df[c_gene].isna().any()" as follows. 

---
Traceback (most recent call last):
    File "/usr/local/bin/intogen-combine", line 8, in <module>
      sys.exit(cli())
    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/intogen_combination/main.py", line 79, in cli
      main(output, **{k: v for k, v in kwargs.items() if v is not None})
    File "/usr/local/lib/python3.9/site-packages/intogen_combination/main.py", line 23, in main
      ranking, pvalues = parser.parse(**files)
    File "/usr/local/lib/python3.9/site-packages/intogen_combination/parser.py", line 74, in parse
      assert not df[c_gene].isna().any()
  AssertionError
---

Why did this happen? 
What is the variable 'c_gene'? 
Should I filter input maf file to include specific gene sets? 

Thank you in advance!

Regards,

**Comment by FedericaBrando** [comment]
Hi, this error is due to the fact that there is a gene in the dataset that is not mapped to any Hugo symbol - most probably in the smregions output file.  Therefore this error.

We are working on a patch that should solve this problem, in the meantime you could check the smregions file and remove this specific gene from the work directory.

We are planning to release the patch pretty soon - before EOY. 

Thanks for your patience. 

Federica

**Comment by RyulKim-Inocras** [comment]
Thanks!
That's why the combination step succeded if only CGC genes were included. 

Another one. 

After the combination step, another error occured in DriverDiscovery step as follows:

---
Traceback (most recent call last):
  File "/usr/local/bin/intogen-combine", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/intogen_combination/main.py", line 79, in cli
    main(output, **{k: v for k, v in kwargs.items() if v is not None})
  File "/usr/local/lib/python3.9/site-packages/intogen_combination/main.py", line 37, in main
    optimized = grid_optimizer.run(ranking.copy(), **files)
  File "/usr/local/lib/python3.9/site-packages/intogen_combination/grid_optimizer.py", line 354, in run
    out_df = full_optimizer(ranking, method_reject, percentage_cgc, seed, **files)
  File "/usr/local/lib/python3.9/site-packages/intogen_combination/grid_optimizer.py", line 315, in full_optimizer
    grid_optimum = grid_optimize(func, low_quality=discarded)  # get optimum candidate in the grid
  File "/usr/local/lib/python3.9/site-packages/intogen_combination/grid_optimizer.py", line 195, in grid_optimize
    for w in itertools.product(np.linspace(0, 1, 21), repeat=dim-1):
ValueError: repeat argument cannot be negative
---

The "dim" is 0, and therefore, repeat argument became -1 and that's why the error occured. 
Why the "dim" became 0? All the previous steps completed succesfully. 

Regards, 

RK

**Comment by RyulKim-Inocras** [comment]
Thanks!

By manually filtering rows with no hugo symbol in SMregions output,
the problem was solved!!

Regards,

RK
